swagger: '2.0'
info:
  description: This is a swagger config for Piana Tech Web Console
  version: 0.1.0
  title: Piana Tech Web Console
schemes:
  - http
paths:
  '/sample':
    get:
      tags:
        - sample
      summary: return a sample related to given id
      operationId: getSample
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: './dto.yaml#/definitions/SampleDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: './dto.yaml#/definitions/ErrorDto'
  '/sample/one':
    get:
      tags:
        - sample
      summary: return a sample related to given id
      operationId: getSampleOne
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: './dto.yaml#/definitions/SampleDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: './dto.yaml#/definitions/ErrorDto'
  '/guest/signup':
    post:
      tags:
        - guest
      summary: return a user
      operationId: signUp
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: './dto.yaml#/definitions/SignupDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: './dto.yaml#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: './dto.yaml#/definitions/ErrorDto'
  '/verify-email/signup/verify':
    post:
      tags:
        - verify-email
      summary: return a user
      operationId: signUpVerify
      produces:
        - application/json
      parameters:
        - in: body
          name: verifyCodeDto
          required: true
          schema:
            $ref: './dto.yaml#/definitions/VerifyCodeDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: './dto.yaml#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: './dto.yaml#/definitions/ErrorDto'
  '/guest/login':
    post:
      tags:
        - guest
      summary: return a user
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginDto
          required: true
          schema:
            $ref: './dto.yaml#/definitions/LoginDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: './dto.yaml#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: './dto.yaml#/definitions/ErrorDto'

