swagger: '2.0'
info:
  description: This is a swagger config for Piana Tech Web Console
  version: 0.1.0
  title: Piana Tech Web Console
host: 'localhost:8080'
basePath: '/api'
schemes:
  - http
paths:
  '/sample':
    get:
      tags:
        - sample
      summary: return a sample related to given id
      operationId: getSample
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/SampleDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/sample/one':
    get:
      tags:
        - sample
      summary: return a sample related to given id
      operationId: getSampleOne
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/SampleDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/guest/signup':
    post:
      tags:
        - guest
      summary: return a user
      operationId: signUp
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: argument
          required: true
          schema:
            $ref: '#/definitions/SignupDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/verify-email/signup/verify':
    post:
      tags:
        - verify-email
      summary: return a user
      operationId: signUpVerify
      produces:
        - application/json
      parameters:
        - in: body
          name: verifyCodeDto
          required: true
          schema:
            $ref: '#/definitions/VerifyCodeDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/guest/login':
    post:
      tags:
        - guest
      summary: return a user
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginDto
          required: true
          schema:
            $ref: '#/definitions/LoginDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/guest/mobile/signup':
    post:
      tags:
        - guest
      summary: signup by mobile
      operationId: mobileSignup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginDto
          required: true
          schema:
            $ref: '#/definitions/MobileSignupDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/guest/mobile/login':
    post:
      tags:
        - guest
      summary: login by mobile
      operationId: mobileLogin
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: loginDto
          required: true
          schema:
            $ref: '#/definitions/MobileLoginDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/guest/mobile/forget-password':
    post:
      tags:
        - guest
      summary: remember password by mobile
      operationId: mobileForgetPassword
      consumes:
        - application/json
      parameters:
        - in: body
          name: loginDto
          required: true
          schema:
            $ref: '#/definitions/ForgetPasswordDto'
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/VerifyCodeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
  '/guest/mobile/verify':
    get:
      tags:
        - guest
      summary: verify mobile number
      operationId: mobileVerify
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation.
          schema:
            $ref: '#/definitions/MeDto'
        '500':
          description: Error occurred during execution of request.
          schema:
            $ref: '#/definitions/ErrorDto'
definitions:
  SampleDto:
    type: object
    properties:
      name:
        type: string
        example: Ali
      message:
        type: string
        example: Hi
    title: SampleDto
  SignupDto:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  VerifyCodeDto:
    type: object
    properties:
      code:
        type: string
  LoginDto:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  MeDto:
    type: object
    properties:
      email:
        type: string
      role:
        $ref: '#/definitions/RoleEnum'
      rule:
        $ref: '#/definitions/RuleEnum'
  RoleEnum:
    type: string
    enum:
      - UNKNOWN
      - GUEST
      - USER
      - SUSPENDED
      - ADMIN
  RuleEnum:
    type: string
    enum:
      - FREE
      - VERIFY_EMAIL
      - REGISTER_MOBILE
      - VERIFY_MOBILE
  MessageDto:
    type: object
    properties:
      timestamp:
        type: integer
        format: int64
      code:
        type: integer
        format: int64
      message:
        type: string
      path:
        type: string
  ErrorDto:
    type: object
    properties:
      timestamp:
        type: integer
        format: int64
      status:
        type: string
      error:
        type: string
      message:
        type: string
      path:
        type: string
  MobileSignupDto:
    type: object
    properties:
      mobile:
        type: string
      email:
        type: string
      password:
        type: string
  MobileLoginDto:
    type: object
    properties:
      mobile:
        type: string
      password:
        type: string
  ForgetPasswordDto:
    type: object
    properties:
      mobile:
        type: string
      newPassword:
        type: string