POST http://localhost:8080/api/auth/signup
Content-Type: application/x-www-form-urlencoded

email=z1@gmail.com&password=1234
###
GET http://localhost:8080/api/static/index

###
GET http://localhost:8080/api/sample
cookie: JSESSIONID=055397BFAC952FF3522D570481C2D81D

###
GET http://localhost:8080/api/sample/one
cookie: JSESSIONID=FE9BDC374D5A33DD97783DFE88FFA0CA

###
POST http://localhost:8080/api/guest/login
Content-Type: application/json

{
  "email": "rahmatii1367@gmail.com",
  "password": "123456"
}
###
OPTIONS http://localhost:8080/api/guest/signup
Origin: http://localhost
Referer: http://localhost/
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type

###
POST http://localhost:8080/api/guest/signup
cookie: JSESSIONID=85A6FB0E891CECA1B53C498BB883FDC8
Content-Type: application/json
Origin: http://localhost
Referer: http://localhost/

{
  "email": "rahmatii1367@gmail.com",
  "password": "123456"
}
###
POST http://localhost:8080/api/verify-email/signup/verify
Content-Type: application/json
cookie: JSESSIONID=11D570C0A7A9979CFD3CAD6A38F2B028

{
  "code": "827415"
}
###
