/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ir.piana.tech.api.service;

import ir.piana.tech.api.dto.ErrorDto;
import ir.piana.tech.api.dto.SampleDto;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-04T17:46:56.145+04:30")

@Api(value = "sample", description = "the sample API")
public interface SampleApi {

    SampleApiDelegate getDelegate();

    @ApiOperation(value = "return a sample related to given id", nickname = "getSample", notes = "", response = SampleDto.class, tags={ "sample", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation.", response = SampleDto.class),
        @ApiResponse(code = 500, message = "Error occurred during execution of request.", response = ErrorDto.class) })
    @RequestMapping(value = "/sample",
        method = RequestMethod.GET)
    default ResponseEntity<SampleDto> getSample() {
        return getDelegate().getSample();
    }


    @ApiOperation(value = "return a sample related to given id", nickname = "getSampleOne", notes = "", response = SampleDto.class, tags={ "sample", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation.", response = SampleDto.class),
        @ApiResponse(code = 500, message = "Error occurred during execution of request.", response = ErrorDto.class) })
    @RequestMapping(value = "/sample/one",
        method = RequestMethod.GET)
    default ResponseEntity<SampleDto> getSampleOne() {
        return getDelegate().getSampleOne();
    }

}
